apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:jUYHAqHLR47LL3gKac4liIduwIHAJ5Do4vvDIBMNduAUzR3dYNNr0A==,iv:mws7gQ7Y3dCmKXLNzOmsLYAHmEiw7u5uhzbB8BoLkyI=,tag:vIQg2HvqT8SfqAo39NrOUw==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTFRGYW5xdFdtVXRlNlds
        UEV3RVhkZTA0Y201ZzhDSU5YcFIxZUh6QW1nCjdtMGNpeXRZcndnRDhBdUZpcDNx
        czN5alAveUNxY05rRTJoY1V3ajMrdGcKLS0tIDVoOEZXaElod1lEa3JFREIyY2Y5
        OWF3cXVoeFUwMDJWYW5vbi8rVHVTaTgKBQZT+r6pMVYrXdWWNZZHYtJ3nT8GzPA4
        Qji/VpLPxA1KeMgIHcZxOEKg4vjKEDXFrbWUVrpVhopaTKb9yuBY6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T05:08:15Z"
  mac: ENC[AES256_GCM,data:aVtWm735djYC6NC8X3u3iSdKS1HPG4h5DpoO9i73BDV89aHn6HyvA9GkruThi0RK2o43J6qC4sPSw6BXokXtcZpOkMCvsXZx5iO+UuN/3+GGodOf7pRjpOv2/e6Y62EbQ7SCheIcXpNf8M05TAJxkWOpoEwqU/Gj7GF6kLFNr0I=,iv:1oDaz3Ky9DNdUVn0fOWPIHi65r6YA0aMH2hHdvzgWSk=,tag:TbcMvY9e71LV8thqQpi4fw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
