apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:E4KYNU2/VwRciRXp7MJGHpfcBcxfHMglqiUPteSIzmetxIS4wrxt7g==,iv:c12s1+WX+Ny0AN1lh4OH6mbFUwE2NBXL8BNXBumuC3M=,tag:7CnlYJApEeG636Gvsydpqw==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMGllV3dPZHdWUis4cWhl
        Qi9nRll5L21jVno5R2V5NXpFVDB5YlZFOWhVCnpVK0NUV1p1dDZOMlBzLy84TkMy
        dDYrUHl0SlFQNGVpeVlRdjFaa1NIM3MKLS0tIHJCb21rY2M4VFRWN2FRR0FZbUhi
        M2Erdk5VaDkvcVduQmtsKzVXZnpYMGsK4jTJJKZJLgukht90cSCrY3tIDWCaeCLa
        JgnS+gGo/iCz3gstVtNm1O99iOGh2Avy+RsTDhomMHjejt5EOBhx3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T01:04:33Z"
  mac: ENC[AES256_GCM,data:GnKG2gYtJwqiLTso7KpJ4Hc9cXzViwFvd6h56lMIMZBnYsvI9g9S+Ig75/sibS5T39tT8EmwNlTavecmMVNjsnJKUFr1uKn17HOcM/ONskAGpQdWOm0wult2MWF2ZVLLNYDB9Fg/cjcQCu68F01fpSGgRyUu6ne0v00a7yFuMU0=,iv:Z/N9ka6c9OKq01tMjF/zmf7JUnQUleCZWZXPLhTKK94=,tag:piAlIrYa9d8kell5Ptn1Fw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
