apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:E+mWLXxH9cmkubs9irKd6KUokKkoJDLajBngkEWBukKKBfxz79XziA==,iv:QJ/RmdY7mS2aKLr12jkX8JsWb4gVL3f99zBc+FaLRRU=,tag:ycYNCBkwit8u5EpjPNeGug==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWmpFS21JM3ZVMDY5WGcw
        cGFNTXJFMlF1cmVMN0tzTTVMaUFLTFlxS0NrCmlPTWZxWkNRcWluMGNPdGVtb3hp
        c3RyUGRMclBiTGtibnNxUFhjcnEyOUkKLS0tIEhIKytndTNtajB6czZMcFNQT2dv
        Wm9yN2wrSi9SWXJraXVKc1RpeEgzUlEKNLRHOuER+enbOuRTwOTu2yX8FQho0eOc
        PD5DPy+GPmluVZT5FKrjJSUGgRcPi+MfSDBEkv4UzE535ZnBkeLvmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T19:30:43Z"
  mac: ENC[AES256_GCM,data:stMIVrgaJqOglDvStJgHr/Em6tg46Qu5EntnaOZH3a/DEMQdsysJ1vTkvf9Y+7PGadFRGN9FrYE9+nfkmvqQY4kszZq22LNI0IhlX4N2N+G0L6QJZz4ZyEuSTU7UMagjyME6aOCyfNpGwXlg4owOK8r2YPG7NoqlR84z6k184lw=,iv:h6iGrMsYMC+MOJDpLWMaLUU5pgZzLlowZDWfzr6MAbA=,tag:87F7wozaIJIVDNtK+kVy/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
