apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KsHHOi27Jw==,iv:7aP6ojN/ux/2kOCRTIeXC+tbp9YQ/4lDAsak0duQFPQ=,tag:5SiHzJBgaFvEq2b0gnJbMg==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTlRacEVBcFB5WjRsOU5N
        MU9uOStGQWNhbE01SWpINVIrT1lYOTBtcEFvCitzZ0pINUxOV0krRFZiRVRnMXE2
        cE9IbFlDd1RxN3pKSzk3SzhQZEd2bGMKLS0tIGcyMndRM1FEd3cvdHpzUWxlaFdy
        Z0VxSU5Sdy9jRmNWUW0wMjhVblA3UzAKSpedJE83rbJ6KeBSCFz6vzBhV/dNZPW1
        oFYBVQwNyvYGS/3k/uO4mG68ikYTb7jYS0RMH0P4ZDTXFempxgLyjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T19:30:42Z"
  mac: ENC[AES256_GCM,data:vb7UaSFAzDXBi1F/RNKVJjnv24KNIagYTytrD+NbbDgzZELIsTNWqhE/KKscFHa9feJ72E8HUKbixvivY3dax7lY5wFMmRPlsWpVm37DG8u7H+hU+5hz4z3WQfKSWfOANMkC3/6y4+6LQH5u1mG6z8FUoZ3JbgRuAVNaEjTTQBU=,iv:94GWF2bAw2fysSKDVg72Muqi7Zn8dV2ZCnwU+5J3WzM=,tag:ocZbergVx0ZyVR5K8biaAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
