apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:IwhN5EkUKQ==,iv:H9U6V7T7TFxp2vJ/kqGBoh1hi00ZzB/h/ErTP86nCyQ=,tag:zb+WNmpLhredbiuK4LpCPw==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbkdGdXdsQU9ZRVhjVlMy
        V3J5cG8vRVlrYWpEbzQxcDJpTmk0aHFaV1g0CjJMRkw3ZU9JQytIY3JoajZWN1JE
        eHdnRXJMdEZGRVNZQm5EaGw5OTFFWmsKLS0tIEw5S0xjZzBOSEpYNnk1OTZ0a2Y5
        RVY2U01Eem9OZDF0OG1YZUl6YU11MmMKFocVFey+4XQv85KuBu1uz8PZR9iNyYJX
        dqu3xNFb3nGpH/QLM5VREqnGB/L4DQKTt7OeScs+wF8TVrzQA57Btg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T23:01:06Z"
  mac: ENC[AES256_GCM,data:2SP6/hplZ1uEx8eocRjLn/kLZBSYKs7pRB99l8bcIVvYxjLjWSXla3oiDB8MfhmDUuUqcYeyoG32vzToxlnPlXaPjVZ0ZC5Oqf6IvgCW1VDHihcTI2ePjDSMZBuMK4QQMJeVs5Oba1tVuqGof3NGs+QIm+C1CYM2qcRYiZ8XYDo=,iv:00mcZr0jAJ2f/PW3e+pOo+zpknjWkpq0hoIkIUMDfa4=,tag:hGjQT7cVsMMkd+EFVn5NlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
