apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:A5xsZxHfyg==,iv:eo6ocet1r5Vy/yyqY9tlBu7r1ke9V3fBd9vs284KV+Q=,tag:ful6wkIhv5L29FThPq0Yhg==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRmI0QlRNQkduQ0FYQlp2
        RzZSQ2hRd0R4emRYaUpXNFEvWVdpR0ErYWlBClFnaHFRd3Q3ZmNLU0FiU0pmOVdK
        VklmbTJiNDdDNFhHdzVPQnpSME1WK0EKLS0tIHFNaTJoMWM4OGRjRGErTzZCTk9z
        SVpYTTczRjR2Q3VpLzFwcVoyS095ZTQKxaN4aHot3pgcCVcvAVMQ97P0DI6NQj+i
        NTs0ZMfN88LzIKImzozyw39WE70vpGxXKMOhGuhGnkFwyrMWnePy3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T05:08:15Z"
  mac: ENC[AES256_GCM,data:GVnwp7LZa1X1JKGdjtwYpPNlVBXbFu6nZOt7IAg7ceBWe4alDfyFzJBpVypnBp5NYKMknmjcJXpoR8aQFVE8qIwdfsitFFXuQvS4zMXiTiJ/G9rE0chdYvphLKiJgynIKXEc7sZYktANRzJOZ8a7ZP8o0I2bU2paK3KOIhudxto=,iv:8InlBm5jbHR+rhouhtONlJjuBpaWEhKGWxhh6x+cAqc=,tag:9a5a+tsvVQP4hIWN0wgyhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
