apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:M/Q9fsJ7QQBbM1XumQurUZm/GlEvrsgZYGvdsL+YQ38=,iv:E54Afb/0NZjwbGGQJq/vsfsSGS65Ako/m80+mVZguT0=,tag:b19hy0DuyiJ0nRDlthklbw==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVHV1Z1B0b1ppOGp6TzJz
        RXNmYWVocWtKb3hsZC9KZ1M3U29BK0RzVGhNCjU1UE9yV3lnNmFnS0Z3NHAxZzI4
        Q0pkbmJnSFYramt1WUxHZExhNk9ERzQKLS0tIDdXc2E0MDRGOFVNcldiQkJsQXdW
        eWVtT0U5eDRaQ0FuR1E4Mm1SUXl5b0UKO2pcdYvIutyryyKcd8RNU+e9+jTMvdCp
        o4162t2lhos1Zz0CdoIpE4ehE2m7zl12aLGSs2wPwTbX1Ngj8MD3hA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T05:08:15Z"
  mac: ENC[AES256_GCM,data:8wJ324e0WeoCOeGbsuS3v4zp0dEj5tUuwqTeQrXv01DH0jwg2fks5BE4NMV1OlqVreuYZ7wMh/f9jX+hyZdJNnJSVwX5Z9Nvpa145LP+hFoXuuCnlZwIMie4cgIpLkYve6STHpY8jvaINduKffCbpdyYEXfj7+W7rBd2NWHrpiE=,iv:cHzQBHFB5MoF1CBvGfj6FM1Ollk3kpYkn2phTOLP7qU=,tag:r9a6BseLpMbu8ZK8SjKwlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
