apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:hBR2O+SnH6nbFB8EfnUNMn3xgB7QK+YL0OmVbWRCFmM=,iv:p117WM59z1E/B0ep6o2pSUqCdgZn4LZaB4RTUS4hqcc=,tag:rWs9VK45d68yA4ZN/yhdaA==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L0hpRC8ycVVlU0Uxa0R6
        Sy9QZ2dRMi9TNXNTcHNUL25wRU1OQ1BwUm5BCmRaUDVhS2M2ejlTR0Mrb0tkTFVi
        WWdZQzF4Mmo4NlVtZHpDaTI3bEYxdncKLS0tIEpxQ3U2QU0ydUlkNTlFUXd5cEE3
        SDh4ejU2cXBzbjBvM29IL3MvN2k3YlUKpP78blCmziJbVWyJKt/dLTmryQfJnF7E
        ILMFL8aUOSuHG4elbfQFk8Uvc/zHiqmrupka4hEYk5sM+m7h/UfNmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T01:04:32Z"
  mac: ENC[AES256_GCM,data:D0N1eaxKR1MMImc9JjD0EhktrkgY3a0WumoGFaJAjVT5rCXLtHMW4Vs9Cd429QDIwolqoF47rFbuE4RXpFekVseFfS8y+Ty+l9AC1YwbyrZZbfYT0ENDFJ8HW7LBdmPBDiwwHJ+t57+kFhp9XRdu7HHPfb73WKycs4XPHgOQaGI=,iv:42izPsyPcdXj6tfrrPOin3kE7da/Q4bRpsOqfEQhT1s=,tag:ew0hM3CLCGqF1d5z8+YYNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
