apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:mrTuYs4f1OcLOPcp0ZM7GAnq1fEK7hSscpWVVUNxu73UxFQLO8H5Kbi62Wmy892iDjD8XNn3aFaHppmxkaW0pprCUlKgIWSPnE4QS5uox8OqaDH0l7JnSLx5YH9aYsuOOzO+KmpT8ITdJfeeSfjqMClRgU8SRnX/QYPsXklI7O7WnRsNpSawidv1ANFFxvCGsQMZi+huUXvPSoq02CwVWARDsbfUeo/SWjDnYbsXXsnTGmru,iv:fuhtWzHcSO5AMXuV2WnJJ6c0fVpdpy2SeC+ENUG//Vk=,tag:RlcwDlwN2XkfX28b3NXGow==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdzh0ZmpNOUlmQzhWY2ZR
        MkVQajhTS0NWU3BTaDkxUHZ6N0JBUldIRUFNCk1sTkVQc2FCTEIvUGpWQ0lWNDFF
        R1daN0hiUzdZK2sxMzJUczdPQWpYUHMKLS0tIGNPNjNtSEJQZ0drbjJ2NEZZcWlu
        eHJjMVFRdlRwcC9ocmlXS2Q2VUNQbzAKa23+EajIHpU0OealL3E47khTQ//m3yh9
        HVMHLbdK7CmFbzalGLajO6clS4jH0ndZo4onqlbY8xxu7y9f3yi6fA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T19:30:43Z"
  mac: ENC[AES256_GCM,data:0n0Duflgwt5IHrX4L372plrnqADXY71bAly6I/ZUNu5iF7N+RfWLqzvp3/4dqJvlDR3YqDqBf/7+tD+OYWL5RZGAaqE56u2WMn1Ig+F4+ETUaj983VUPAK0E1jCHpb59Jw9h9MWp53L/TIk49ZlfemjbL3rCwrZZCnSA298DbLo=,iv:1pB5KDMMZfAdlu3/CeUZ2Sl8YJAIpyotP0wdeYLZqeQ=,tag:0yE8ZcaAX1OqHszHbPV+Rw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
