apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:zX2rrgwDGVgdGeAdcn4hQsTUz3YFLIxlgq/plv8x4Rnon+6ZxRf/YrU9MgBxbrqcQ/9468fnwslkUd1NcqMd6y7qX3uj40h8qSsERD5srbIC3F2PXTMQx8KPDlqt3l6yKfBQCfRgmyDIevQWycDIYEJ+ZTRAbWfRwU8C0iez9X0MqHbDV3kiXWlhvPOcitmP844QzBayzGbb55nmbCDOale6hPYHx3E2VFeG3beGJykdZJvZ,iv:/zYhEY4xANjOvG61t+zkYpXDll/QTgUHuV2nVgWynGw=,tag:5xZGfZRCxliib4Qv5N8ruQ==,type:str]
sops:
    age:
        - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKazdvZDF0UlhjL0RkNXdC
            U05OcFgwSE5CcXhhb0RiblJXdWM5cTlrWmg4ClhHdFFpZlAyS1pCU0Z2SXZtUzV0
            cS8yck5Gdlh4OWw2c0QvN05XQTNSNHMKLS0tIDF0OWRBa2VDQTZlMStUT0N1SmdP
            TDN4TXRETDlNcDROcEZqcUpzUzk0VkUKdfyW/9h7B7qbF6eTt8DSQ7xI5qgb+0IF
            P0TjkzH68IOQaQpa4AT9JR2OTvSBRcaMaHVVEHrd/o6mGk12TQ78xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T01:29:49Z"
    mac: ENC[AES256_GCM,data:QtcJMvTXEup24Ahg/D7wMF5PFTDw98gyQ1I6/8kTTzvvxBKsdnsnJdoeTThTWszHkOSI2ACRGbrcroDR4yqMcvNB2coXUSX15YfYZnohJlOkOUNy13z+RsczztxrajMnhb+i/4hXSQmGa28ciFQu2YBezQv4VpsInPH+8QLfAhY=,iv:XJ7BiX1jWBGmUdIDbZZMaDEe6WtH6tNpfceuRyX0BxE=,tag:zhlrnN0jEMv3G2u2rozEVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
