apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:/a511OoMdAPSUcLDzsyOgJjgPOkM6TiaHFWGqiBqEWIfzx6aY7byTSVmPqddQRTRAHkmjGOZ82HOdC8gcoCXTvBFfaDQgj0tMucGD0r9uKtVAIqEOv0ex/NZeP2Mq9UU5yG1rpcokz0YPVWEcunD1xN6nU3FYaY2YGatC/RLtMdOyYGTYdCMCHnzGMi6VBB6v21Fkj0wn4l3OL3spuauL+giMg76/G/fURfzR8TYhHBalmhf,iv:GWJqn1l8FEJaf4dFES4uHOQWRBTmDvsJRc+bvWGXsiQ=,tag:yUvExxZGTQ9k9hVS7JKMaw==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDU2NQUjlIN1NHeTBzbWxV
        UGN1T3JEMktMNEZiQmxLOUhReFR5emVyU3g4CmNCMGhST1g5TmZncnZ5K1FTdVBy
        dFplK0hHRjRXZW9LZE91d3Vab0tCdm8KLS0tIHZpZmJxdVkwRVppMzE2U3ZCWUI4
        RjFGbjVOK3JZZEo2ejgxZGJRNU9HTlkKT0/hkxXlcezHYVusIttwHzZp16WgT7RZ
        ES5BFguE619Y3F7a3eSTmxcp39itNuYqNWcpIdVlGa7D3eYlhdBytQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T23:01:06Z"
  mac: ENC[AES256_GCM,data:r5GerCAN02VOnsyv9AymwoXAXSuLhk15ttTglXLaUXfObKy/EoCXSe5K2s4x3odsV5DIJ4qVAD7Yj4zb/HYrZyHnCZFOAutnu8uIqPIl4rRO3yLQRG64zIiiLiJj3+kp4wOuqp6Nx1G2kNF3EIq9ieZN0N/SHTIjNs4oEHd42VM=,iv:mps5pShLsLtkfxdOw4MY5hj8BgumFhoHuapYfS6vwgU=,tag:nG281+2Bp8XPF5zluK0vRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
