apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:hK/hkvuuluQ2cqonpOEGWOmIH2U0Hd6Dz0/UDQDKiH1xj/QEdUNYVg==,iv:WZEApD2drLhkUVvjY2BylJG0nfUl+b5Nc0gN8yfi7z8=,tag:VyTh+EJw5TQV3CsAwAkzGg==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NmFTSXBnRE9melMrd0FD
        dzlCTis1NW9TNUNqZ2RtQjR5eVJmZWNycXlZCkcvbE14K2duWXZ4VVBKS3JEaGhJ
        TEhtei9OUnBGV21Nc0dzVjU2V0l6TmMKLS0tIHhzeWxzVDkxalBoL3J0RXh0bXht
        dmFLNTFmSkF3eit3YnRLYmpHRlQ3VFUK9cvISdY/miE/jD2p6ZW6anZABgQsAWOl
        /hvwrHWSeoxaPOmxzsCvyHUgLItMqMGq8q12YwM3NfX50PVgbGB8Dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T05:08:15Z"
  mac: ENC[AES256_GCM,data:C/x9dmi+FcU9KKNMmdazoQ0EazCXhLAkIPbHJV6fbeo7bmsnFQap0tiHefkHJrVp5l6ZhYwqBJJuR3cO8hhMZPXqLom+x57aBwUg6b1yblWPUB+xINvzDEzgc3eHOZG8OWXt4s27H8RJbSgZiSmpEHp36F/eqeNgwUOUS915juY=,iv:HXAeqxRFaI6L4gD/OO293L0CuFtoAUeUxX9KF/GkZWw=,tag:LMJ1uR6T4lt91T7mdkcyBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
