apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:nhJ1ykDNuPkTVJ8Y+9sfLclYmKfg7M/KzS45JLRB7zeXvlk/ExLonQ==,iv:giiDs70cXWCi/ui6c66ahNCaPeP+SwAsUcwCH8Jnyj0=,tag:9qVOKG/aJbAS+RCoMwp4cA==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSFdYdlhicG9Fd29jUVpz
        dm1DWXNXN1dsc2N3T09vOVAreCtkQzNIQVd3Clhyc01xZEpSc254NUU3bXBjVzRW
        c1ZsZGxCRUM3SDdveVlLS0YxZHNlcmsKLS0tIE14MzgxRHl0M1FQay9TU1NyWGs2
        Zklqc0lReE10NGRrZW9zbFpSc0tCajAK/XYQ6/kknFJwA6RBiYP9dpQcLmnmwkAT
        4gtMqxM9XSg53t307DraYynDVf3HZhiQnymQHPocUbcN3lUnp5kwFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T23:01:06Z"
  mac: ENC[AES256_GCM,data:ZjrKcuRjZdMkn7gqA02UklA9whI3U93Di+/H8eXVkAZVYmord4Zq0NPspL05T+w2kXwcK7IxQcYVnG67tjNJCVadY5FnKC+K+c/hGhnnRYeRBERgmH6uEyD1S3fT4B2aGak9HRfP+rGJbAQi0f2+0WyDIJJdW7ZsHk5ZXj5irsI=,iv:zx7LdGZ6eS781f65AJycnlrZUFGSg8YEwPJ5Tz1kHBI=,tag:YcPR6tTdFGb5InmAGOYJ/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
