apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:UEVN4El65EAyHRw2JGyOMDJcmY4fkqFsenjLlyaF5b+uY7pwhTwFuw==,iv:SCX4L3LiKd2m975ji+F0jRnOna8RTx925xUyIgqycto=,tag:K/O7bsrzuMKSxZapxYzDtA==,type:str]
sops:
  age:
    - recipient: age15e3g09ku9u6czvdefutrxg9qew0eyfwrpx8ufj6sty2tve3nue3s7fyqtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUEN1KzNJOVNFVVZGRnRu
        eGRRL3lQQUpRUXpmNkV0NlJ6QWxVTmVMZEJZCkd6NjU4LzZCcXVsckdhYWNWMG1G
        dUQ3ZzR2RFBPSHhhM3laTXlvSnJkRncKLS0tIHpveERDc012T1hMSDdTc0xVdk9H
        bWY1bGljWGRROUVCNm80V3V0R294STQKUQlE6SGTrWOzqhRS7evjbPn127j0icp8
        dESS59QL+uCX7Udp+HTCTARNwVfBN1pZrdDMPhhOLGVyNwSZcPbDpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T01:04:33Z"
  mac: ENC[AES256_GCM,data:MyfEwg4afpYHWQZqcn/7sC2OqHatwSqsbuU3qpZ0HdpOGaCwV9DAKk5o13qsmDpkwHEOVAvgxMQCs7S4Pv7iZh3tioSXdtLipT3ubmcBkBOuGxj7TEFn5rVvevPhF8Md9Syz4SJzy0PRq8WjoUIYz0lixWTlTxJIVhoN2S3/6Kk=,iv:d269w4bCm2t+ovoCAFhgx9uXcMdRjpmrjiWo/72s9zA=,tag:ReYBmkjtmerpjbmy0s3Ldw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
